name: sprint1_project
description: "A new Flutter project."

publish_to: 'none' # This is a private project

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Medium.ttf
        - asset: assets/Poppins-Bold.ttf
          weight: 700
